name: uni_size
description: "A comprehensive Flutter package for responsive UI design with universal sizing units that work consistently across all platforms. Provides .dp for sizes and .sp for fonts with automatic scaling based on screen density and text scale factors."
version: 1.0.0
homepage: https://github.com/jagadeeshchoudhary/uni_size
repository: https://github.com/jagadeeshchoudhary/uni_size
issue_tracker: https://github.com/jagadeeshchoudhary/uni_size/issues
documentation: https://github.com/jagadeeshchoudhary/uni_size#readme

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test_cov_console: ^0.2.2


flutter:

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - responsive
  - ui
  - design
  - sizing
  - scaling

license: MIT
