name: uni_size
description: "A Flutter package for responsive design using .dp and .sp units that scale with device screen and text settings. Works consistently on all platforms."
version: 1.0.3
homepage: https://github.com/jagadeeshchoudhary/uni_size
repository: https://github.com/jagadeeshchoudhary/uni_size
issue_tracker: https://github.com/jagadeeshchoudhary/uni_size/issues
documentation: https://github.com/jagadeeshchoudhary/uni_size#readme

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test_cov_console: ^0.2.2


flutter:

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - responsive
  - ui
  - design
  - sizing
  - scaling

license: MIT
